import { LitElement, css, html } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';

/**
 * The 3D colour picker — extracted verbatim from the Tactile Kit's Color section.
 *
 * The kit's picker is a self-contained THREE.js application (a hue ring, an
 * HSV/RGB/Lab/HCL slice, a live 3D model of the space, a palette builder). It is
 * lifted byte-for-byte into a standalone document (`/kit/color-picker.html`,
 * generated by `scripts/build-color-picker.js` from the same source) and mounted
 * here in an iframe, so the picker's own code runs completely unchanged — nothing
 * about it is reinterpreted. The chosen colour is bridged out via `postMessage`.
 *
 * Defaults to Hyle's violet #8E7BFF, exactly as the kit's picker does.
 *
 * @element hy-color-picker
 * @attr value - The selected colour (hex). Reflected; also the initial colour.
 * @fires hy-change - `detail.value` (hex) whenever the picker's colour changes.
 */
@customElement('hy-color-picker')
export class HyColorPicker extends LitElement {
  /** Selected colour as a hex string. */
  @property({ reflect: true }) value = '#8e7bff';
  /** Path to the generated standalone picker document. */
  @property() src = '/kit/color-picker.html';

  @query('iframe') private _frame?: HTMLIFrameElement;
  @state() private _height = 560;

  private _onMessage = (e: MessageEvent) => {
    // Only accept messages from our own iframe's window.
    if (!this._frame || e.source !== this._frame.contentWindow) return;
    const d = e.data;
    if (!d || typeof d !== 'object') return;
    if (d.type === 'hy-color' && typeof d.value === 'string') {
      const v = d.value.trim();
      if (v && v.toLowerCase() !== this.value.toLowerCase()) {
        this.value = v;
        this.dispatchEvent(
          new CustomEvent('hy-change', { detail: { value: v }, bubbles: true, composed: true })
        );
      }
    } else if (d.type === 'hy-height' && typeof d.value === 'number' && d.value > 0) {
      this._height = Math.ceil(d.value) + 4;
    }
  };

  connectedCallback() {
    super.connectedCallback();
    window.addEventListener('message', this._onMessage);
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    window.removeEventListener('message', this._onMessage);
  }

  private get _url() {
    const v = (this.value || '').replace(/^#/, '');
    return v ? `${this.src}?value=%23${v}` : this.src;
  }

  static styles = css`
    :host {
      display: block;
      width: 100%;
      max-width: 392px;
    }
    iframe {
      display: block;
      width: 100%;
      border: 0;
      background: transparent;
      color-scheme: normal;
    }
  `;

  render() {
    return html`
      <iframe
        part="frame"
        src=${this._url}
        title="Hyle colour picker"
        scrolling="no"
        style="height:${this._height}px"
      ></iframe>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'hy-color-picker': HyColorPicker;
  }
}
