import StyleDictionary from 'style-dictionary';

/**
 * Hyle Design System — token build pipeline.
 *
 * Source of truth: /tokens/*.json (W3C DTCG format, $value/$type).
 * One definition compiles to every platform:
 *   - Web    → CSS custom properties, SCSS, JS/JSON
 *   - Android→ colors.xml + dimens.xml resources
 *   - iOS    → Swift constants
 */

// --- Custom transforms -------------------------------------------------------
// Dimension tokens are stored unitless; each platform applies its own unit.

StyleDictionary.registerTransform({
  name: 'hyle/size/px',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const v = parseFloat(t.$value);
    return v === 0 ? '0' : `${v}px`;
  },
});

StyleDictionary.registerTransform({
  name: 'hyle/size/dp',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const v = parseFloat(t.$value);
    // Type scale uses scale-independent pixels (sp) on Android; everything else dp.
    const unit = t.path[0] === 'font' ? 'sp' : 'dp';
    return `${v}${unit}`;
  },
});

StyleDictionary.registerTransform({
  name: 'hyle/size/pt',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => `${parseFloat(t.$value)}`,
});

// Durations are stored as unitless milliseconds; web wants the `ms` suffix.
StyleDictionary.registerTransform({
  name: 'hyle/time/ms',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'duration',
  transform: (t) => `${parseFloat(t.$value)}ms`,
});

// Kotlin (Compose-free :hyle module) wants plain integers, no unit suffix.
StyleDictionary.registerTransform({
  name: 'hyle/size/int',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => `${Math.round(parseFloat(t.$value))}`,
});

StyleDictionary.registerTransform({
  name: 'hyle/time/int',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'duration',
  transform: (t) => `${Math.round(parseFloat(t.$value))}`,
});

// --- Custom formats ----------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'hyle/android-colors',
  format: ({ dictionary }) => {
    const rows = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => `  <color name="${t.name}">${t.$value}</color>`);
    return `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${rows.join('\n')}\n</resources>\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'hyle/android-dimens',
  format: ({ dictionary }) => {
    const rows = dictionary.allTokens
      .filter((t) => t.$type === 'dimension')
      .map((t) => `  <dimen name="${t.name}">${t.$value}</dimen>`);
    return `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${rows.join('\n')}\n</resources>\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'hyle/kotlin',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => `        const val ${t.name}: Argb = 0x${t.$value.replace('#', '').toUpperCase()}L`);
    const dims = dictionary.allTokens
      .filter((t) => t.$type === 'dimension')
      .map((t) => `        const val ${t.name}: Int = ${t.$value}`);
    const durations = dictionary.allTokens
      .filter((t) => t.$type === 'duration')
      .map((t) => `        const val ${t.name}: Int = ${t.$value}`);
    return [
      '// Generated by Style Dictionary (`npm run tokens:build`). Do not edit by hand.',
      '// Source of truth: /tokens/*.json — the same tokens the web build consumes.',
      'package dev.aarso.hyle.tokens',
      '',
      'import dev.aarso.hyle.Argb',
      '',
      '/** Compiled Hyle design tokens, shared with the web and iOS builds. */',
      'object HyleTokens {',
      '    /** ARGB colours (0xAARRGGBB). */',
      '    object Color {',
      colors.join('\n'),
      '    }',
      '',
      '    /** Dimensions, in density-independent pixels (dp; type scale is sp). */',
      '    object Dimension {',
      dims.join('\n'),
      '    }',
      '',
      '    /** Durations, in milliseconds. */',
      '    object Duration {',
      durations.join('\n'),
      '    }',
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'hyle/ios-swift',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => `    public static let ${t.name} = ${t.$value}`);
    const dims = dictionary.allTokens
      .filter((t) => t.$type === 'dimension')
      .map((t) => `    public static let ${t.name}: CGFloat = ${t.$value}`);
    return [
      'import UIKit',
      '',
      '/// Auto-generated by Style Dictionary. Do not edit.',
      'public enum HyleTokens {',
      '  public enum Color {',
      colors.join('\n'),
      '  }',
      '  public enum Size {',
      dims.join('\n'),
      '  }',
      '}',
      '',
    ].join('\n');
  },
});

// --- Platforms ---------------------------------------------------------------

const webTransforms = ['attribute/cti', 'name/kebab', 'color/css', 'hyle/size/px', 'hyle/time/ms'];

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  log: { verbosity: 'default' },
  platforms: {
    css: {
      transforms: webTransforms,
      buildPath: 'build/web/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transforms: webTransforms,
      buildPath: 'build/web/',
      files: [{ destination: '_tokens.scss', format: 'scss/variables' }],
    },
    js: {
      transforms: ['attribute/cti', 'name/camel', 'color/css', 'hyle/size/px', 'hyle/time/ms'],
      buildPath: 'build/web/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.json', format: 'json/nested' },
      ],
    },
    // Android resources land directly in the publishable :hyle library module,
    // so web and Android share one token source.
    android: {
      transforms: ['attribute/cti', 'name/snake', 'color/hex8android', 'hyle/size/dp'],
      buildPath: 'hyle/src/main/res/values/',
      files: [
        { destination: 'hyle_tokens_colors.xml', format: 'hyle/android-colors' },
        { destination: 'hyle_tokens_dimens.xml', format: 'hyle/android-dimens' },
      ],
    },
    // Compose-free Kotlin token object, consumed alongside Finish/Pulse/RadiantHues.
    kotlin: {
      transforms: ['attribute/cti', 'name/camel', 'color/hex8android', 'hyle/size/int', 'hyle/time/int'],
      buildPath: 'hyle/src/main/java/dev/aarso/hyle/tokens/',
      files: [{ destination: 'HyleTokens.kt', format: 'hyle/kotlin' }],
    },
    ios: {
      transforms: ['attribute/cti', 'name/camel', 'color/UIColorSwift', 'hyle/size/pt'],
      buildPath: 'build/ios/',
      files: [{ destination: 'Tokens.swift', format: 'hyle/ios-swift' }],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
console.log('\n✔ Tokens built for web, android, ios → /build');
