import StyleDictionary from 'style-dictionary';

/**
 * Hyle Design System — token build pipeline.
 *
 * Source of truth: /tokens/*.json (W3C DTCG format, $value/$type).
 * One definition compiles to every platform:
 *   - Web    → CSS custom properties, SCSS, JS/JSON
 *   - Android→ colors.xml + dimens.xml resources
 *   - iOS    → Swift constants
 */

// --- Custom transforms -------------------------------------------------------
// Dimension tokens are stored unitless; each platform applies its own unit.

StyleDictionary.registerTransform({
  name: 'hyle/size/px',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const v = parseFloat(t.$value);
    return v === 0 ? '0' : `${v}px`;
  },
});

StyleDictionary.registerTransform({
  name: 'hyle/size/dp',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const v = parseFloat(t.$value);
    // Type scale uses scale-independent pixels (sp) on Android; everything else dp.
    const unit = t.path[0] === 'font' ? 'sp' : 'dp';
    return `${v}${unit}`;
  },
});

StyleDictionary.registerTransform({
  name: 'hyle/size/pt',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => `${parseFloat(t.$value)}`,
});

// --- Custom formats ----------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'hyle/android-colors',
  format: ({ dictionary }) => {
    const rows = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => `  <color name="${t.name}">${t.$value}</color>`);
    return `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${rows.join('\n')}\n</resources>\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'hyle/android-dimens',
  format: ({ dictionary }) => {
    const rows = dictionary.allTokens
      .filter((t) => t.$type === 'dimension')
      .map((t) => `  <dimen name="${t.name}">${t.$value}</dimen>`);
    return `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${rows.join('\n')}\n</resources>\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'hyle/ios-swift',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => `    public static let ${t.name} = ${t.$value}`);
    const dims = dictionary.allTokens
      .filter((t) => t.$type === 'dimension')
      .map((t) => `    public static let ${t.name}: CGFloat = ${t.$value}`);
    return [
      'import UIKit',
      '',
      '/// Auto-generated by Style Dictionary. Do not edit.',
      'public enum HyleTokens {',
      '  public enum Color {',
      colors.join('\n'),
      '  }',
      '  public enum Size {',
      dims.join('\n'),
      '  }',
      '}',
      '',
    ].join('\n');
  },
});

// --- Platforms ---------------------------------------------------------------

const webTransforms = ['attribute/cti', 'name/kebab', 'color/css', 'hyle/size/px'];

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  log: { verbosity: 'default' },
  platforms: {
    css: {
      transforms: webTransforms,
      buildPath: 'build/web/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transforms: webTransforms,
      buildPath: 'build/web/',
      files: [{ destination: '_tokens.scss', format: 'scss/variables' }],
    },
    js: {
      transforms: ['attribute/cti', 'name/camel', 'color/css', 'hyle/size/px'],
      buildPath: 'build/web/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.json', format: 'json/nested' },
      ],
    },
    android: {
      transforms: ['attribute/cti', 'name/snake', 'color/hex8android', 'hyle/size/dp'],
      buildPath: 'build/android/',
      files: [
        { destination: 'colors.xml', format: 'hyle/android-colors' },
        { destination: 'dimens.xml', format: 'hyle/android-dimens' },
      ],
    },
    ios: {
      transforms: ['attribute/cti', 'name/camel', 'color/UIColorSwift', 'hyle/size/pt'],
      buildPath: 'build/ios/',
      files: [{ destination: 'Tokens.swift', format: 'hyle/ios-swift' }],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
console.log('\n✔ Tokens built for web, android, ios → /build');
