import type { Preview } from '@storybook/web-components';

// Token layer — generated by `npm run tokens:build` into /build/web.
import '../build/web/tokens.css';
// Register every custom element.
import '../src/components/index.js';

const preview: Preview = {
  parameters: {
    layout: 'centered',
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    backgrounds: {
      default: 'field',
      values: [
        { name: 'field', value: '#000000' },
        { name: 'near', value: '#0a0809' },
        { name: 'raised', value: '#121212' },
      ],
    },
    options: {
      storySort: {
        order: ['Introduction', 'Foundations', 'Material', 'Tactile', 'Displays', 'Controls', 'Surfaces', 'Mock Apps'],
      },
    },
  },
};

export default preview;
