import type { Preview } from '@storybook/web-components';

// Token layer — generated by `npm run tokens:build` into /build/web.
import '../build/web/tokens.css';
// Register every custom element.
import '../src/components/index.js';

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    backgrounds: {
      default: 'canvas',
      values: [
        { name: 'canvas', value: '#f7f8fa' },
        { name: 'surface', value: '#ffffff' },
        { name: 'inverse', value: '#161a23' },
      ],
    },
    options: {
      storySort: {
        order: ['Introduction', 'Foundations', 'Components'],
      },
    },
  },
};

export default preview;
