import type { Preview } from '@storybook/web-components';
import hyle from './hyle-theme';

// Brand fonts — Archivo (UI/display) + JetBrains Mono (data voice).
import '@fontsource-variable/archivo';
import '@fontsource-variable/jetbrains-mono';
// Token layer — generated by `npm run tokens:build` into /build/web.
import '../build/web/tokens.css';
// Register every custom element.
import '../src/components/index.js';

const preview: Preview = {
  parameters: {
    layout: 'centered',
    docs: { theme: hyle },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    backgrounds: {
      default: 'field',
      values: [
        { name: 'field', value: '#000000' },
        { name: 'near', value: '#0a0809' },
        { name: 'raised', value: '#121212' },
      ],
    },
    options: {
      storySort: {
        order: [
          'Introduction',
          'Signature',
          'Material',
          'Mock Apps',
          'Foundations',
          'Tactile',
          'Displays',
          'Controls',
          'Surfaces',
        ],
      },
    },
  },
};

export default preview;
